name: Create Empty Commit
on:
  workflow_dispatch:
jobs:
  create_empty_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Show Branch Name
        run: echo Branch ${GITHUB_REF##*/}
      - name: Create and Checkout New Dev branch
        run: git checkout ${GITHUB_REF##*/}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Create Empty Commit
        run: git commit --allow-empty -m "Empty commit"
      - name: Push Commit
        run: git push
