name: HACS Validate

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.2.0"
      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
